"""make industry_id nullable

Revision ID: 086b02814597
Revises: 99fee3334562
Create Date: 2026-04-08 13:21:12.181928

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '086b02814597'
down_revision: Union[str, Sequence[str], None] = '99fee3334562'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('product', 'industry_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('product', 'industry_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
