"""changed product search reult to suppor brand

Revision ID: 65e417895e43
Revises: cc521d81aaf7
Create Date: 2026-04-23 17:26:51.561658

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '65e417895e43'
down_revision: Union[str, Sequence[str], None] = 'cc521d81aaf7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('productsearchresult', sa.Column('brand', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    op.add_column('productsearchresult', sa.Column('category', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    op.add_column('productsearchresult', sa.Column('product_type', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    op.add_column('productsearchresult', sa.Column('product_ids', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('productsearchresult', 'product_ids')
    op.drop_column('productsearchresult', 'product_type')
    op.drop_column('productsearchresult', 'category')
    op.drop_column('productsearchresult', 'brand')
    # ### end Alembic commands ###
