"""added shopify auth

Revision ID: 6ecd5491bea7
Revises: 85c0d09d9dcb
Create Date: 2026-05-11 18:35:07.222619

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '6ecd5491bea7'
down_revision: Union[str, Sequence[str], None] = '85c0d09d9dcb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('shopify_auth_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_product_shopify_auth_id'), 'product', ['shopify_auth_id'], unique=False)
    op.create_foreign_key(None, 'product', 'shopifyauth', ['shopify_auth_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'product', type_='foreignkey')
    op.drop_index(op.f('ix_product_shopify_auth_id'), table_name='product')
    op.drop_column('product', 'shopify_auth_id')
    # ### end Alembic commands ###
