"""added file name

Revision ID: 8bb2c7d80b55
Revises: de7356818fc1
Create Date: 2026-04-29 15:44:13.102074

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '8bb2c7d80b55'
down_revision: Union[str, Sequence[str], None] = 'de7356818fc1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appimport', sa.Column('file_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('appimport', 'file_name')
    # ### end Alembic commands ###
