"""added brand and product type

Revision ID: 99fee3334562
Revises: d877007da323
Create Date: 2026-04-01 17:16:16.256729

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '99fee3334562'
down_revision: Union[str, Sequence[str], None] = 'd877007da323'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brand',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('brand_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_brand_brand_name'), 'brand', ['brand_name'], unique=True)
    op.create_table('product_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('product_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_type_product_type'), 'product_type', ['product_type'], unique=True)
    op.add_column('product', sa.Column('brand_id', sa.Integer(), nullable=True))
    op.add_column('product', sa.Column('product_type_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'product', 'brand', ['brand_id'], ['id'])
    op.create_foreign_key(None, 'product', 'product_type', ['product_type_id'], ['id'])
    op.drop_column('product', 'brand')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('brand', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'product', type_='foreignkey')
    op.drop_constraint(None, 'product', type_='foreignkey')
    op.drop_column('product', 'product_type_id')
    op.drop_column('product', 'brand_id')
    op.drop_index(op.f('ix_product_type_product_type'), table_name='product_type')
    op.drop_table('product_type')
    op.drop_index(op.f('ix_brand_brand_name'), table_name='brand')
    op.drop_table('brand')
    # ### end Alembic commands ###
